modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="alloyer_sun"
version="1.0.0"
displayName="Alloyer Uranium - Sun"
authors="You"
description='''More silver ore (extra veins, boosted Fortune) for electrum, plus the Alloyer recipe: lapis + electrum + hydrogen -> 2 uranium.'''

[[dependencies.alloyer_sun]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.alloyer_sun]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.alloyer_sun]]
modId="mekanism"
type="required"
versionRange="[10.7,)"
ordering="AFTER"
side="BOTH"

[[dependencies.alloyer_sun]]
modId="mekanismsun"
type="required"
versionRange="[1.2.0,)"
ordering="AFTER"
side="BOTH"
